<?php

namespace AppBundle\Repository;

/**
 * GraphRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GraphRepository extends \Doctrine\ORM\EntityRepository
{
}
