<?php

namespace AppBundle\Repository;

/**
 * TimelineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimelineRepository extends \Doctrine\ORM\EntityRepository
{
}
